Articles/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Social.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Social/urls.py
from venv import create
from django.urls import path
from .views import *


urlpatterns = [
    path('',homeView,name='home'),
    path('login/',loginView,name='login'),
    path('register/',registerView,name='register'),
    path('logout/',logoutView,name='logout'),
    path('createArticle/',createArticle,name='createArticle'),
    path('details/<str:pk>/',detailsView,name='details'),
    path('deleteArticle/<str:pk>/',deleteArticle,name='deleteArticle'),
    path('updateArticle/<str:pk>/',updateArticle,name='updateArticle'),
    path('deleteComment/<str:pk>/',deleteComment,name='deleteComment'),
    path('like/<str:pk>/',like,name='like'),
    path('dislike/<str:pk>/',dislike,name='dislike'),
    path('profile/',profile,name='profile'),
    path('addComment/<str:pk>',addComment,name='addComment')
]

Social/models.py
from email.policy import default
from io import open_code
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    username = models.CharField(null=True,max_length=50)
    Avatar = models.ImageField(null=True,default='avatar.svg')
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username+" "+self.email+" "+str(self.is_superuser)

class Topic(models.Model):
    Name = models.CharField(max_length=30)
    NoArticles = models.IntegerField(default=0)
    def __str__(self):
        return self.Name +" "+ str(self.NoArticles)

class Article(models.Model):
    Topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    Content = models.TextField(max_length=1000)
    Owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name="author")
    updated_at = models.DateTimeField(null=True,auto_now=True)
    created_at = models.DateTimeField(null=True,auto_now_add=True)
    noLike = models.PositiveIntegerField(default=0)
    noDislike = models.PositiveIntegerField(default=0)
    userLike = models.ManyToManyField(User,related_name="Users_like_article")
    userDisLike = models.ManyToManyField(User,related_name="User_dislike_article") 
    def __str__(self):
        return str(self.Topic) + " "+self.Content[:100]+" "+str(self.Owner)
    class Meta:
        ordering = ('-updated_at','-created_at')


class Like(models.Model):
    user = models.ForeignKey(User,related_name="liked_user",on_delete=models.CASCADE)
    article = models.ForeignKey(Article,related_name="liked_article",on_delete=models.CASCADE)
    like = models.BooleanField(default=False)

class Comment(models.Model):
    Owner = models.ForeignKey(User,on_delete=models.CASCADE)
    Article = models.ForeignKey(Article,on_delete=models.CASCADE)
    Content = models.TextField(max_length=200)
    updated = models.DateTimeField(null=True,auto_now=True)
    created = models.DateTimeField(null=True,auto_now_add=True)
    def __str__(self):
        return str(self.Owner) +" "+str(self.Article)+" "+self.Content
    
    class Meta:
        ordering = ('-updated','-created')

Social/forms.py
from .models import *
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm


class myUserCreation(UserCreationForm):

    class Meta:
        model = User
        fields =['username','email','password',]

class UserFormUpdate(ModelForm):

    class Meta:
        model = User
        fields =  ['Avatar','username','email']

class UserForm(ModelForm):
    
    class Meta:
        model = User
        fields = ['username','password','email']

class TopicForm(ModelForm):
    
    class Meta:
        model = Topic
        fields = '__all__'

class ArticleForm(ModelForm):
    
    class Meta:
        model = Article
        fields = '__all__'

class CommentForm(ModelForm):
    
    class Meta:
        model = Comment
        fields = '__all__'

Social/views.py
from django.shortcuts import render,redirect
from .models import Article, Topic,User,Comment,Like
from django.db.models import Q
from django.contrib.auth import login,logout,authenticate
from .forms import UserForm, UserFormUpdate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
# Create your views here.

def homeView(request):
    topics = Topic.objects.all()[0:20]
    q = request.GET.get('q')
    topic = request.GET.get('topic')
    if topic is not None:
        try:
           articles = Article.objects.filter(Topic__Name=topic)
        except:
            articles = {}
    else:
        if q is None:
            q = ''
        articles = Article.objects.filter(
            Q(Content__icontains=q)
            )
    articles = articles[0:20]
    numberOfArticles = articles.count()
    allArticle = Article.objects.all().count()
    context = {"topics":topics,"articles":articles,"NoArticle":numberOfArticles,"allArticle":allArticle}
    return render(request,'Social/index.html',context)

def loginView(request):
    message = ""
    if request.user.is_authenticated:
        return redirect('home')
    if(request.method.lower()=="post"):
        userEmail = request.POST.get('email').lower()
        userPassword = request.POST.get('password')
        try:
            user = User.objects.get(email=userEmail)
        except:
            message = "please enter a valid email or password"
        user = authenticate(request,email=userEmail,password=userPassword)
        print(user)
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            message ="please enter a correct password"
            
    context = {"login":True,"message":message}
    return render(request,'Social/login-register.html',context)

def registerView(request):
    message = ''
    if request.user.is_authenticated:
        return redirect('home')
    form = UserForm()
    if request.method == 'POST':
        user_email = request.POST.get('email')
        try:
            User.objects.get(username=user_email)
            message = "this email is already exist try sign in"
        except:
            user = UserForm(request.POST)
            if user.is_valid():
                user = user.save(commit=False)
                user.username = user.username.lower()
                user.email = user.email.lower()
                user.password = make_password(user.password)
                user.save()
                login(request,user)
                return redirect('home')
            else:
                message = "some thing wrong with your registration"
    context = {"login":False,"message":message,"form":form}
    return render(request,'Social/login-register.html',context)

def logoutView(request):
    logout(request)
    return redirect('home')

@login_required(login_url='/login')
def createArticle(request):
    if request.method == 'POST':
        Content = request.POST.get('Content')
        Owner = request.user
        topicName = request.POST.get("topicName")
        try:
            topic = Topic.objects.get(Name=topicName)
        except:
            topic = Topic.objects.create(Name=topicName)
        article = Article.objects.create(Owner=Owner,Content=Content,Topic=topic)
        if article is not None:
            topic.NoArticles+=1
            topic.save()
            return redirect('home')

    topics = Topic.objects.all()
    context= {"topics":topics,"value":"Add"}
    return render(request,'Social/addArticle.html',context)

def detailsView(request,pk):
    article = Article.objects.get(id = int(pk))
    topics = Topic.objects.all()
    comments = Comment.objects.filter(Article=article)
    noComments = comments.count()
    numberOfArticles = Article.objects.all().count()
    #print(article)
    try:
        action = Like.objects.get(user=request.user,article=article)
        like = action.like
        dislike = not(like)
    except:
        like = False
        dislike = False
    allArticle = Article.objects.all().count()
    context = {"allArticle":allArticle,"like":like,"dislike":dislike,"article":article,"topics":topics,'comments':comments,"noComments":noComments,"NoArticle":numberOfArticles}
    return render(request,'Social/details.html',context)

@login_required(login_url='/login')
def addComment(request,pk):
    article = Article.objects.get(id = int(pk))
    if request.method == 'POST':
        content = request.POST.get('comment')
        Comment.objects.create(Content=content,Owner=request.user,Article=article)
        return redirect('details',pk=int(pk))

@login_required(login_url='/login')
def deleteArticle(request,pk):
    article = Article.objects.get(id=int(pk))
    article.Topic.NoArticles-=1
    article.Topic.save()
    if article.Topic.NoArticles==0:
        article.Topic.delete()
    article.delete()
    return redirect('home')

@login_required(login_url='/login')
def updateArticle(request,pk):
    article = Article.objects.get(id=int(pk))
    if request.method=='POST':
        Content = request.POST.get('Content')
        Owner = request.user
        topicName = request.POST.get("topicName")
        article.Topic.NoArticles-=1
        article.Topic.save()
        if article.Topic.NoArticles==0:
            article.Topic.delete()
        article.Content = Content
        article.Owner = Owner
        try:
            topic = Topic.objects.get(Name=topicName)  
        except:
            topic = Topic.objects.create(Name=topicName)
        article.Topic = topic
        article.Topic.NoArticles+=1
        article.Topic.save()
        article.save()
        return redirect('home')
    topics = Topic.objects.all()
    context= {"topics":topics,"article":article,"value":"Update"}
    return render(request,'Social/addArticle.html',context)

@login_required(login_url='/login')
def deleteComment(request,pk):
    comment = Comment.objects.get(id=int(pk))
    article = comment.Article.id
    comment.delete()
    return redirect('details',pk=article)

@login_required(login_url='/login')
def dislike(request,pk):
    article = Article.objects.get(id=int(pk))
    try:
        action = Like.objects.get(user=request.user,article = article)
        if action.like:
            action.like = False
            article.noLike-=1
            article.noDislike+=1
            article.save()
            action.save()
        else:
            article.noDislike-=1
            article.save()
            action.delete()
    except:
        Like.objects.create(user=request.user,article=article,like=False)
        article.noDislike+=1
        article.save()
    return redirect('details',pk=pk)
    

@login_required(login_url='/login')
def like(request,pk):
    article = Article.objects.get(id=int(pk))
    try:
        action = Like.objects.get(user=request.user,article = article)
        if action.like:
            article.noLike-=1
            article.save()
            action.delete()
        else:
            action.like = True
            article.noLike+=1
            article.noDislike-=1
            article.save()
            action.save()
    except:
        Like.objects.create(user=request.user,article=article,like=True)
        article.noLike+=1
        article.save()
    return redirect('details',pk=pk)

@login_required(login_url='/login')
def profile(request):
    topics = Topic.objects.all()
    numberOfArticles = Article.objects.all().count()
    user = User.objects.get(id=request.user.id)
    form = UserFormUpdate(instance=user)
    if request.method == "POST":
        print(request.FILES)
        form = UserFormUpdate(request.POST,request.FILES,instance=user)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return redirect('profile')
    allArticle = Article.objects.all().count()
    context = {"allArticle":allArticle,"topics":topics,"NoArticle":numberOfArticles,"user":user,"form":form}
    return render(request,'Social/profile.html',context)

Social/templates/Social/addArticle.html
{% extends 'main.html' %}

{% block content%}
<div class="mw-100 mh-75 p-2 m-md-auto mt-2 mt-md-5" style="width:500px;height:500px">
    <form method="Post" class="form-control d-flex flex-column align-items-center">
        {% csrf_token%}
        <div class="form-outline w-100">
            <label class="form-label" for="room_topic">Enter your article topic</label>
            <input class="form-control mt-2 w-50" required type="text" value="{{article.Topic.Name}}" name="topicName"
                list="topic-list" />
            <datalist id="topic-list">
                <select id="article_topic">
                    {% for topic in topics %}
                    <option value="{{topic.Name}}">{{topic.Name}}</option>
                    {% endfor %}
                </select>
            </datalist>
        </div>
        <div class="form-outline w-100">
            <label class="form-label" for="article-content">Content</label>
            <textarea rows="10" class="w-100 form-control p-4" id="article-content" value="{{article.Content}}" required name="Content">{{article.Content}}</textarea>
        </div>
        <input type="submit" class="ms-auto btn btn-primary my-5" value="{{value}}">
    </form>
</div>
{% endblock %}

Social/templates/Social/articleTopics.html
<div class="mw-75 mb-3 m-0" style="width:300px">
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample"
        aria-expanded="True" aria-controls="collapseExample">
        Browser Topics
    </button>
    <div class="collapse show" id="collapseExample">
        <div class="d-flex justify-content-between align-items-center my-2">
            <div>
                <a href="{% url 'home' %}"><span>All</span></a>
            </div>
            <div>
                <span class="bg-secondary rounded-circle me-3 p-2 text-white">{{allArticle}}</span>
            </div>
        </div>
        <hr>
        {% for i in topics %}
        <div class="d-flex justify-content-between align-items-center my-3">
            <a href="{% url 'home'%}?topic={{i.Name}}">
                <span>{{i.Name}}</span>
            </a>
            <div>
                <span class="bg-secondary rounded-circle me-3 p-2 text-white">{{i.NoArticles}}</span>
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>
</div>

Social/templates/Social/articles.html
{%load static %}
<div class="w-100 container m-1 h-auto">
    <div class="d-flex justify-content-between">
        <div>
            <h6>ARTICLES</h6>
            <p>{{NoArticle}} article</p>
        </div>
        <div>
            <a href="{% url 'createArticle'%}" class="btn btn-primary">Add new Article</a>
        </div>
    </div>
    {% for i in articles%}
    <div class="w-100 bg-secondary shadow border rounded p-2 mt-3 h-auto">
        <div class="d-flex align-items-center justify-content-between">
            <div>
                <img class="rounded rounded-circle" src="{%static i.Owner.Avatar.url%}" style="height:5vh;width:5vh;">
                <span class="m-2 text-white">{{i.Owner.username}}</span>
            </div>
            <div>
                <span class="text-white">{{i.created_at|timesince}} ago</span>
                {%if i.Owner == request.user%}
                <a class="btn btn-info p-1 m-0" href="{% url 'updateArticle' i.id%}">Update</a>
                <a class="btn btn-danger p-1 m-0" href="{% url 'deleteArticle' i.id%}"><i class="fa fa-trash"></i></a>
                {%endif%}
            </div>
        </div>
        <hr>
        <div class="text-white">
            <p class="text-break">{{i.Content|slice:"0:100"}}
                <span><a class="link text-bold" href="{% url 'details' i.id%}">see more</a></span>
            </p>
        </div>
    </div>

    {% endfor %}
</div>

Social/templates/Social/details.html
{% extends 'main.html' %}

{% block content %}

<div class="container mw-100 d-flex mt-5 flex-column flex-md-row" style="width:1100px;">
    {%include 'Social/articleTopics.html'%}
    {%include 'Social/review.html' %}
</div>

{% endblock %}

Social/templates/Social/index.html
{%extends 'main.html' %}


{%block content %}

<div class="container mw-100 d-flex mt-5 flex-column flex-md-row" style="width:1100px;">
    {%include 'Social/articleTopics.html' %}
    {%include 'Social/articles.html'%}
</div>

{% endblock content %}

Social/templates/Social/info.html
{% load static %}
<div class="m-1 m-md-4 mw-100" style="width: 1100px;">
    <form method="post" enctype="multipart/form-data" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div>
            <img class="rounded rounded-circle" src="{%static request.user.Avatar.url%}" class=""
                style="width:15vh;height:15vh;" alt="user avatar">
        </div>
        <h6>Avatar</h6>
        <div class="mt-2 form-outline w-100 d-flex align-items-center">
            <label class="form-label me-3" for="id_Avatar">Change</label>
            <input type="file" name="Avatar" accept="image/*" id="id_Avatar" class="form-control">
        </div>
        <div class="mt-2 form-outline w-100 align-items-center">
            <label class="form-label" for="id_username">Username:</label>
            <input class="form-control" type="text" name="username" value="{{request.user.username}}" maxlength="50"
                required="" id="id_username">
        </div>
        <div class="mt-2 form-outline w-100 align-items-center">
            <label class="form-label" for="id_email">Email:</label>
            <input class="form-control" type="email" name="email" value="{{request.user.email}}" maxlength="254"
                required="" id="id_email">
        </div>
        <input type="submit" class="btn btn-lg btn-primary mt-4" value="Update">
    </form>
</div>

Social/templates/Social/login-register.html
{% extends 'main.html'%}

{% block content %}
{% if login %}
<form method="Post" class="d-flex flex-column bg-white p-4 shadow border border-4 m-auto align-items-center mt-5"
    style="width: 300px;">
    {% csrf_token %}
    <div>
        <h4>LOGIN</h4>
    </div>
    {% if message %}
    <div>
        <small class="text-danger">{{message}}</small>
    </div>
    {% endif %}
    <!-- Email input -->
    <div class="form-outline w-100 mb-4">
        <label class="form-label" for="form2Example1">Email address</label>
        <input name="email" type="email" id="form2Example1" class="form-control" />
    </div>
    <!-- Password input -->
    <div class="form-outline mb-4 w-100">
        <label class="form-label" for="form2Example2">Password</label>
        <input name="password" type="password" id="form2Example2" class="form-control" />
    </div>
    <p>Not a member? <a href="{%url 'register'%}">Register</a></p>
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4 mx-auto">Sign in</button>
</form>
{% else %}
<form method="Post" class="d-flex flex-column bg-white p-4 shadow border border-4 m-auto align-items-center mt-5"
    style="width: 300px;">
    {% csrf_token %}
    <div>
        <h4>Register</h4>
    </div>
    {% if message %}
    <div>
        <small class="text-danger">{{message}}</small>
    </div>
    {% endif %}
    <div class="form-outline w-100">
        <label class="form-label" for="id_username">Username:</label>
        <input name="username" type="text" id="id_username" maxlength="50" required class="form-control" />
    </div>
    <div class="form-outline w-100">
        <label class="form-label" for="id_email">Email:</label>
        <input name="email" type="email" id="id_email" maxlength="254" required class="form-control" />
    </div>
    <div class="form-outline w-100">
        <label class="form-label" for="id_password">password</label>
        <input name="password" type="password" id="id_password" maxlength="128" required class="form-control" />
    </div>
    <div class="form-outline w-100">
        <label class="form-label" for="form3Example4cd">Repeat your password</label>
        <input name="password2" type="password" id="form3Example4cd" class="form-control" />
    </div>
    <div>
        <h6>already have account <a href="{% url 'login'%}">login</a></h6>
    </div>
    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
        <button type="submit" class="btn btn-primary btn-lg">Register</button>
    </div>
</form>
{% endif%}
{% endblock %}

Social/templates/Social/profile.html
{% extends 'main.html' %}

{% block content %}

<div class="container mw-100 d-flex mt-5 flex-column flex-md-row" style="width:1100px;">
    {%include 'Social/articleTopics.html'%}
    {%include 'Social/info.html' %}
</div>

{% endblock %}

Social/templates/Social/review.html
{% load static %}
<div class="m-1 m-md-4 mw-100" style="width: 1100px;">
    <div class="bg-secondary shadow border rounded p-2 mt-3">
        <div class="d-flex align-items-center justify-content-between">
            <div>
                <img class="rounded rounded-circle" src="{%static article.Owner.Avatar.url%}" style="height:5vh;width:5vh;">
                <span class="m-2 text-white">{{article.Owner.username}}</span>
            </div>
            <div>
                <span class="text-white">{{article.created_at|timesince}} ago</span>
                {%if article.Owner == request.user%}
                <a class="btn btn-info p-1 m-0" href="{% url 'updateArticle' article.id%}">Update</a>
                <a class="btn btn-danger p-1 m-0" href="{% url 'deleteArticle' article.id%}"><i class="fa fa-trash"></i></a>
                {%endif%}
            </div>
        </div>
        <hr>
        <div class="m-1 m-md-4">
            <p class="text-break text-white">
                {{article.Content}}
            </p>
        </div>
        <hr>
        <div class="d-flex">
            {%if like%}
            <a href="{%url 'like' article.id%}" class="btn" style="color:blue"><i class="fa fa-thumbs-up fa-lg m-2" aria-hidden="true"></i>like ({{article.noLike}})</a>
            {%else%}
            <a href="{%url 'like' article.id%}" class="btn"><i class="fa fa-thumbs-up fa-lg m-2" aria-hidden="true"></i>like ({{article.noLike}})</a>
            {%endif%}
            {%if dislike%}
            <a href="{%url 'dislike' article.id%}" class="btn" style="color:red"><i class="fa fa-thumbs-down fa-lg m-2" aria-hidden="true"></i>dislike ({{article.noDislike}})</a>
            {%else%}
            <a href="{%url 'dislike' article.id%}" class="btn"><i class="fa fa-thumbs-down fa-lg m-2" aria-hidden="true"></i>dislike ({{article.noDislike}})</a>
            {%endif%}
        </div>
        <div>
            <form action="{% url 'addComment' article.id%}" method="POST">
                {%csrf_token%}
                <div class="d-flex">
                    <textarea name="comment" maxlength="200" required class="form-control m-2" rows="2"
                        placeholder="add a comment"></textarea>
                    <input class="btn btn-primary m-2" type="submit" value="Comment">
                </div>
            </form>
        </div>
    </div>
    <div>
        <h6 class="text-white mt-4">Comments <span class="me-3 text-white">({{noComments}})</span></h6>
        {% for i in comments%}
        <div class="w-100 bg-secondary shadow border rounded p-2 mt-3 h-auto">
            <div class="d-flex align-items-center justify-content-between">
                <div>
                    <img class="rounded rounded-circle" src="{%static i.Owner.Avatar.url%}" style="height:5vh;width:5vh;">
                    <span class="m-2 text-white">{{i.Owner.username}}</span>
                </div>
                <div>
                    <span class="text-white">{{i.created|timesince}} ago</span>
                    {%if i.Owner == request.user%}
                    <a class="btn btn-danger p-1 m-0" href="{% url 'deleteComment' i.id%}"><i
                            class="fa fa-trash"></i></a>
                    {%endif%}
                </div>
            </div>
            <hr>
            <div class="text-white">
                <p class="text-break">{{i.Content}}
            </div>
        </div>
        {% endfor %}
    </div>
</div>